---
title: "Insert the Chapter or Lab Report name here"
author: "Insert your name(s) here"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r load-packages, message=FALSE}
library(tidyverse)
library(ggplot2)
library(vegan)
```

# set working directory for all chunks in this file (default working directory is wherever Rmd file is)
```{r, setup, include=FALSE}
# knitr::opts_knit$set(root.dir = 'set/working/directory/here')
```

## Part 1 PCA
```{r}
#lets read the data into a variable
env_data<-read.csv("Enviornmental_Data.csv",header=TRUE,stringsAsFactors = TRUE)

str(env_data)

#lets scale out data (PCA is sensitive to variable scaling)

scaled_env<- scale(env_data[, c("canopy_percent", "leaf_litter", "grass_height")])

#lets run the actual PCA
#This will show how much variance each principal component explains

pca_result<- prcomp(scaled_env, center = TRUE, scale = TRUE)
summary(pca_result)

```

## Part 2 PCA 

```{r}
#Now lets visualize the PCA
#first lets create a new data frame
pca_data<- as.data.frame(pca_result$x)

#Below we are insertting the habitat variables into the data frame we created above 
pca_data$habitat <- env_data$habitat

#lets make the actual plot now
ggplot(pca_data, aes(x= PC1, y = PC2, color = habitat))+
  geom_point(size= 3)+
  theme_minimal()+
  labs(tittle = "PCA of Evironmental Variables")+
  scale_color_manual(values = c("grassland" = "#1f78b4", 
                                "forest" = "#33a02c", 
                                "edge" = "#e31a1c"))
#lets make the actual plot now
ggplot(pca_data, aes(x= PC1, y = PC3, color = habitat))+
  geom_point(size= 3)+
  theme_minimal()+
  labs(tittle = "PCA of Evironmental Variables")+
  scale_color_manual(values = c("grassland" = "#1f78b4", 
                                "forest" = "#33a02c", 
                                "edge" = "#e31a1c"))
#lets make the actual plot now
ggplot(pca_data, aes(x= PC3, y = PC2, color = habitat))+
  geom_point(size= 3)+
  theme_minimal()+
  labs(tittle = "PCA of Evironmental Variables")+
  scale_color_manual(values = c("grassland" = "#1f78b4", 
                                "forest" = "#33a02c", 
                                "edge" = "#e31a1c"))
```
## Lets check which variables drive separation: 
```{r}
loadings <- as.data.frame(pca_result$rotation)

print(loadings)
```


## Lets check for significant differnces using a permanova
```{r}
# First, calculate a distance matrix (using Euclidean distance)
dist_matrix <- dist(scaled_env)


#Then, run PERMANOVA using the adonis2() function from vegan:

library(vegan)

result <- adonis2(dist_matrix ~ habitat, data = env_data)
print(result)




```

```{r}
#lets see which habitats are different?
install.packages("remotes")
remotes::install_github("pmartinezarbizu/pairwiseAdonis/pairwiseAdonis")
library(pairwiseAdonis)

pairwise_result <- pairwise.adonis(scaled_env, env_data$habitat)
print(pairwise_result)



```



