---
title: "Assessing Lyme Disease Risk in Dynamic Ecotonal Communities"
author: "Gerardo Ramos"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---
# Introduction
&nbsp;&nbsp;&nbsp;&nbsp;Despite current efforts vector borne diseases like Lyme disease, transmitted in the western United States by the Ixodes pacificus tick, are emerging with greater frequency [1]. In humans, Lyme disease causes long term chronic arthritic, cardiac and dermatologic manifestations [2]. Assessing vector borne disease risk and understanding the web of transmission remains important for identifying stages in the transmission cycle where the vector and pathogen can be disrupted to reduce abundance in the environment. Disease risk is difficult to predict in the western United States, where I. pacificus feeds on a diverse set of vector meal hosts with contrasting effects on the disease risk [3]. I. pacificus has three host-seeking life stages where it can acquire Borrelia burgdorferi through horizontal transmission (i.e., from a reservoir host, not the parents) [4]. During its larval and nymphal stage, I. pacificus feeds primarily on small rodents and lizards, including the western fence lizard, dusky-footed woodrat , deer mouse, and western gray squirrel [5], [6]. Each species has different habitat preferences: N. fuscipes favor dense oak woodlands, while P. maniculatus occupy a broader range of habitats from woodlands to grasslands7. These two species are the primary reservoir hosts for B. burgdorferi through which I. pacificus can become infected. S. occidentalis, the preferred meal host of I. pacificus, is abundant in areas where there is sufficient basking habitat8. This species poses an interesting variable in the transmission cycle because it clears I. pacificus from the B. burgdorferi infection; however, it contributes to maintenance of high I. pacificus densities [6].  
&nbsp;&nbsp;&nbsp;&nbsp;Ecotones are areas of ecological transition that experience rapid changes in abiotic conditions and community composition9. These unique conditions present in ecotones can influence the distribution of vector meals in the environment defining the epidemiological landscape [10]. However, little work has been done assessing disease risk along ecotonal communities in California. Therefore, for this study my aims will be to: 1) Understand differences in tick density between a oak woodland and annual grassland, habitat gradient. 2) Understand differences in infection prevalence between a oak woodland and annual grassland, habitat gradient. I expect to observe the greatest infection prevalence in oak woodlands, and the lowest in ecotone communities. Conversely, I expect tick densities to be greatest in ecotone communities and lower in oak woodland. Understanding how vector hosts and ticks behave on habitat edges is important in the face of human expansion and land use change [1]. Fragmentation of habitats can lead to greater human interaction between humans and wildlife through the displacement of species and the expansion of the urban-wildlife interface11. The study here will investigate how vectors and disease dynamics behave at habitat edges. However, it will also inform how species will respond to fragmentation, the creation of new habitat boundaries and edges between natural habitats and human settlements.  





# References
[1] Swei, A. et al. 2020. Vector Borne Zoonotic Dis. [3] Seltzer, E.G. et al. 2000. JAMA. [3] McDonald, A.J. et al. 2016. Ticks and Tick-borne Diseases. [4] Kwan, J.Y. et al. 2017. Mol Ecol. [5] Lane, R.S. et al. 2005. J Med Entomol. [6] Swei, A. et al. 2011. Proc Biol Sci. [7] Fellers, G. M. et al. 1994. Southwest Nat. [8] Swei, A. et al. 2011. Oecologia. [9] Marañón, T. et al. 1994. Madroño. [10] Despommier, D. et al. 2006. Ecohealth. [11] Lawrence, A. et al. 2018. Ecosphere.
